spring:
  profiles:
    active: docker-builder

  data:
    redis:
      host: localhost
      port: 45000

  datasource: 
    url: jdbc:mysql://localhost:44000/tradedb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
