services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "${GAME_TRADE_SYSTEM_REDIS_PORT:-6379}:6379"
    command: >
      redis-server
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru

  db:
    image: mysql:8.4
    ports:
      - "${GAME_TRADE_SYSTEM_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tradedb
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    name: ${GAME_TRADE_SYSTEM_DB_VOLUME_NAME:-db-data}
    external: true
