package com.example.tradedemo.common.exception;

import com.example.tradedemo.common.consts.ErrorMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorEnum {
    // Item
    ERR_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_ITEM_NOT_FOUND),

    // MarketListing
    ERR_MARKET_LISTING_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MARKET_LISTING_NOT_FOUND),

    // Auth
    ERR_AUTH_INVALID_TOKEN(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_INVALID_TOKEN),
    ERR_AUTH_EXPIRED_TOKEN(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_EXPIRED_TOKEN),
    ERR_AUTH_DUPLICATE_EMAIL(HttpStatus.CONFLICT, ErrorMessage.MSG_AUTH_DUPLICATE_EMAIL),
    ERR_AUTH_DUPLICATE_NICKNAME(HttpStatus.CONFLICT, ErrorMessage.MSG_AUTH_DUPLICATE_NICKNAME),
    ERR_AUTH_MEMBER_NOT_FOUND(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_MEMBER_NOT_FOUND),
    ERR_AUTH_INVALID_PASSWORD(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_INVALID_PASSWORD),
    ERR_AUTH_WITHDRAWN_MEMBER(HttpStatus.FORBIDDEN, ErrorMessage.MSG_AUTH_WITHDRAWN_MEMBER),
    ERR_AUTH_SUSPENDED_MEMBER(HttpStatus.FORBIDDEN, ErrorMessage.MSG_AUTH_SUSPENDED_MEMBER),

    // Member
    ERR_MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_NOT_FOUND),
    ERR_MEMBER_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_ITEM_NOT_FOUND),
    ERR_MEMBER_HAS_ACTIVE_LISTINGS(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_MEMBER_HAS_ACTIVE_LISTINGS),
    ERR_MEMBER_HAS_PENDING_ASSETS(HttpStatus.CONFLICT, ErrorMessage.MSG_MEMBER_HAS_PENDING_ASSETS),


    // Coupon
    ERR_COUPON_POLICY_DUPLICATE_NAME(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_DUPLICATE_NAME),
    ERR_COUPON_POLICY_FIRST_COME_QUANTITY_REQUIRED(
            HttpStatus.BAD_REQUEST, ErrorMessage.MSG_COUPON_POLICY_FIRST_COME_QUANTITY_REQUIRED),
    ERR_COUPON_POLICY_AUTO_SIGNUP_ALREADY_EXISTS(
            HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_AUTO_SIGNUP_ALREADY_EXISTS),
    ERR_COUPON_ALREADY_ISSUED(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_ALREADY_ISSUED);

    private final HttpStatus httpStatus;
    private final String errorMessage;
}
