package com.example.tradedemo.common.exception;

import com.example.tradedemo.common.consts.ErrorMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorEnum {
    // Item
    ERR_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_ITEM_NOT_FOUND),
    ERR_INVENTORYITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_INVENTORYITEM_NOT_FOUND),

    // MarketListing
    ERR_MARKET_LISTING_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MARKET_LISTING_NOT_FOUND),
    ERR_MARKET_LISTING_OWNER_MISMATCH(HttpStatus.FORBIDDEN, ErrorMessage.MSG_MARKET_LISTING_OWNER_MISMATCH),
    ERR_MARKET_LISTING_OVER_SELLING(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_MARKET_LISTING_OVER_SELLING),
    ERR_MARKET_LISTING_FORBIDDEN_FROM_CANCEL(
            HttpStatus.FORBIDDEN, ErrorMessage.MSG_MARKET_LISTING_FORBIDDEN_FROM_CANCEL),
    ERR_MARKET_LISTING_ILLEGAL_CANCEL_STATUS(
            HttpStatus.CONFLICT, ErrorMessage.MSG_MARKET_LISTING_ILLEGAL_CANCEL_STATUS),

    // Auth
    ERR_AUTH_INVALID_TOKEN(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_INVALID_TOKEN),
    ERR_AUTH_EXPIRED_TOKEN(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_EXPIRED_TOKEN),
    ERR_AUTH_DUPLICATE_EMAIL(HttpStatus.CONFLICT, ErrorMessage.MSG_AUTH_DUPLICATE_EMAIL),
    ERR_AUTH_DUPLICATE_NICKNAME(HttpStatus.CONFLICT, ErrorMessage.MSG_AUTH_DUPLICATE_NICKNAME),
    ERR_AUTH_MEMBER_NOT_FOUND(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_MEMBER_NOT_FOUND),
    ERR_AUTH_INVALID_PASSWORD(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_INVALID_PASSWORD),
    ERR_AUTH_WITHDRAWN_MEMBER(HttpStatus.FORBIDDEN, ErrorMessage.MSG_AUTH_WITHDRAWN_MEMBER),
    ERR_AUTH_SUSPENDED_MEMBER(HttpStatus.FORBIDDEN, ErrorMessage.MSG_AUTH_SUSPENDED_MEMBER),
    ERR_AUTH_SOCIAL_ACCOUNT_ONLY(HttpStatus.FORBIDDEN, ErrorMessage.MSG_AUTH_SOCIAL_ACCOUNT_ONLY),
    ERR_AUTH_SOCIAL_UNLINK_FORBIDDEN(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_AUTH_SOCIAL_UNLINK_FORBIDDEN),
    ERR_AUTH_SOCIAL_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_AUTH_SOCIAL_NOT_FOUND),
    ERR_AUTH_SOCIAL_UNSUPPORTED_PROVIDER(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_AUTH_SOCIAL_UNSUPPORTED_PROVIDER),
    ERR_AUTH_NOT_ACTIVE_STATUS(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_AUTH_NOT_ACTIVE_STATUS),
    ERR_AUTH_PASSWORD_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_AUTH_PASSWORD_ALREADY_EXISTS),

    // Member
    ERR_MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_NOT_FOUND),
    ERR_MEMBER_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_ITEM_NOT_FOUND),
    ERR_MEMBER_HAS_ACTIVE_LISTINGS(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_MEMBER_HAS_ACTIVE_LISTINGS),
    ERR_MEMBER_HAS_PENDING_ASSETS(HttpStatus.CONFLICT, ErrorMessage.MSG_MEMBER_HAS_PENDING_ASSETS),

    // Coupon
    ERR_COUPON_POLICY_DUPLICATE_NAME(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_DUPLICATE_NAME),
    ERR_COUPON_POLICY_FIRST_COME_QUANTITY_REQUIRED(
            HttpStatus.BAD_REQUEST, ErrorMessage.MSG_COUPON_POLICY_FIRST_COME_QUANTITY_REQUIRED),
    ERR_COUPON_ALREADY_ISSUED(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_ALREADY_ISSUED),
    ERR_COUPON_POLICY_AUTO_SIGNUP_ALREADY_EXISTS(
            HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_AUTO_SIGNUP_ALREADY_EXISTS),
    ERR_MEMBER_COUPON_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_COUPON_NOT_FOUND),
    ERR_COUPON_POLICY_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_COUPON_POLICY_NOT_FOUND),
    ERR_COUPON_POLICY_SOLD_OUT(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_SOLD_OUT),
    ERR_COUPON_NOT_USABLE(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_NOT_USABLE),
    ERR_COUPON_EXPIRED(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_EXPIRED),
    ERR_COUPON_LOCK_CONFLICT(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_LOCK_CONFLICT),

    // Wallet
    ERR_WALLET_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_WALLET_NOT_FOUND),

    // Order
    ERR_WALLET_INSUFFICIENT_BALANCE_BAD_REQUEST(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_WALLET_INSUFFICIENT_BALANCE_BAD_REQUEST),
    ERR_MARKET_LISTING_NOT_SELLING(HttpStatus.CONFLICT, ErrorMessage.MSG_MARKET_LISTING_NOT_SELLING),

    // pending
    ERR_PENDING_ASSET_FOUND_EXCEPTION(HttpStatus.NOT_FOUND, ErrorMessage.MSG_PENDING_ASSET_FOUND_EXCEPTION),
    ERR_PENDING_ASSET_ALREADY_CLAIMED(HttpStatus.NOT_FOUND, ErrorMessage.MSG_PENDING_ASSET_ALREADY_CLAIMED),
    ERR_PENDING_ASSET_FORBIDDEN(HttpStatus.FORBIDDEN, ErrorMessage.MSG_PENDING_ASSET_FORBIDDEN),
    ERR_PENDING_ASSET_EXPIRED_EXCEPTION(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_PENDING_ASSET_EXPIRED_EXCEPTION),
    ERR_LOCK_INTERRUPTED(HttpStatus.INTERNAL_SERVER_ERROR, ErrorMessage.MSG_LOCK_INTERRUPTED),
    ERR_LOCK_ACQUIRE_FAILED(HttpStatus.CONFLICT, ErrorMessage.MSG_LOCK_ACQUIRE_FAILED),

    // Chat
    ERR_CHAT_ROOM_LISTING_ALREADY_EXISTS(HttpStatus.CONFLICT, ErrorMessage.MSG_CHAT_ROOM_LISTING_ALREADY_EXISTS),
    ERR_CHAT_ROOM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_CHAT_ROOM_NOT_FOUND);

    private final HttpStatus httpStatus;
    private final String errorMessage;
}
