package com.example.tradedemo.common.exception;

import com.example.tradedemo.common.consts.ErrorMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorEnum {
    // Item
    ERR_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_ITEM_NOT_FOUND),
    ERR_INVENTORYITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_INVENTORYITEM_NOT_FOUND),

    // MarketListing
    ERR_MARKET_LISTING_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MARKET_LISTING_NOT_FOUND),
    ERR_MARKET_LISTING_OWNER_MISMATCH(HttpStatus.FORBIDDEN, ErrorMessage.MSG_MARKET_LISTING_OWNER_MISMATCH),
    ERR_MARKET_LISTING_OVER_SELLING(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_MARKET_LISTING_OVER_SELLING),

    // Auth
    ERR_AUTH_INVALID_TOKEN(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_INVALID_TOKEN),
    ERR_AUTH_EXPIRED_TOKEN(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_EXPIRED_TOKEN),
    ERR_AUTH_DUPLICATE_EMAIL(HttpStatus.CONFLICT, ErrorMessage.MSG_AUTH_DUPLICATE_EMAIL),
    ERR_AUTH_DUPLICATE_NICKNAME(HttpStatus.CONFLICT, ErrorMessage.MSG_AUTH_DUPLICATE_NICKNAME),
    ERR_AUTH_MEMBER_NOT_FOUND(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_MEMBER_NOT_FOUND),
    ERR_AUTH_INVALID_PASSWORD(HttpStatus.UNAUTHORIZED, ErrorMessage.MSG_AUTH_INVALID_PASSWORD),
    ERR_AUTH_WITHDRAWN_MEMBER(HttpStatus.FORBIDDEN, ErrorMessage.MSG_AUTH_WITHDRAWN_MEMBER),
    ERR_AUTH_SUSPENDED_MEMBER(HttpStatus.FORBIDDEN, ErrorMessage.MSG_AUTH_SUSPENDED_MEMBER),

    // Member
    ERR_MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_NOT_FOUND),
    ERR_MEMBER_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_ITEM_NOT_FOUND),

    // Coupon
    ERR_COUPON_POLICY_DUPLICATE_NAME(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_DUPLICATE_NAME),
    ERR_COUPON_POLICY_FIRST_COME_QUANTITY_REQUIRED(
            HttpStatus.BAD_REQUEST, ErrorMessage.MSG_COUPON_POLICY_FIRST_COME_QUANTITY_REQUIRED),
    ERR_COUPON_ALREADY_ISSUED(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_ALREADY_ISSUED),
    ERR_COUPON_POLICY_AUTO_SIGNUP_ALREADY_EXISTS(
            HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_AUTO_SIGNUP_ALREADY_EXISTS),
    ERR_MEMBER_COUPON_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_MEMBER_COUPON_NOT_FOUND),
    ERR_COUPON_POLICY_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_COUPON_POLICY_NOT_FOUND),
    ERR_COUPON_POLICY_SOLD_OUT(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_POLICY_SOLD_OUT),
    ERR_COUPON_NOT_USABLE(HttpStatus.CONFLICT, ErrorMessage.MSG_COUPON_NOT_USABLE),

    // Wallet
    ERR_WALLET_NOT_FOUND(HttpStatus.NOT_FOUND, ErrorMessage.MSG_WALLET_NOT_FOUND),

    // Order
    ERR_WALLET_INSUFFICIENT_BALANCE_BAD_REQUEST(HttpStatus.BAD_REQUEST, ErrorMessage.MSG_WALLET_INSUFFICIENT_BALANCE_BAD_REQUEST);

    private final HttpStatus httpStatus;
    private final String errorMessage;
}
